org.xpect.ui/src/org/xpect/ui/util/ContentTypeUtil.java
=> dont log errors the user cannot do anything about #168

org.eclipse.xtext.example.arithmetics.xpect.tests/pom.xml, org.eclipse.xtext.example.domainmodel.xpect.tests/pom.xml, org.xpect.releng/integration-tests/org.xpect.integrationtest.eclipse_4_4_0.xtext_2_7_3/pom.xml, org.xpect.releng/integration-tests/org.xpect.integrationtest.eclipse_4_5_0.xtext_2_8_3/pom.xml, org.xpect.releng/integration-tests/org.xpect.integrationtest.eclipse_4_5_0.xtext_2_8_4/pom.xml, org.xpect.releng/maven-plugin-parent/pom.xml, org.xpect.releng/maven-test-parent/pom.xml, pom.xml
This Pullrequests
- updates tycho version to 0.26.0
- fixes build failing to optional mac deps beeing pulled anyway
=> Fix build on non mac machines/in maven

org.xpect.xtext.lib.tests/src/org/xpect/xtext/lib/tests/tests/XtextTestsTest.java, org.xpect.xtext.lib.tests/src/org/xpect/xtext/lib/tests/tests/linking.xtext.xt, org.xpect.xtext.lib/src/org/xpect/xtext/lib/tests/LinkingTest.java
=> Support EList in linkedFragment

org.eclipse.xpect.releng/maven-plugin-parent/pom.xml, org.eclipse.xtext.example.arithmetics.xpect.tests/pom.xml, org.eclipse.xtext.example.domainmodel.xpect.tests/pom.xml
=> bumped tycho version to 1.3.0

org.eclipse.xpect.releng/target-platforms/eclipse_4_10_0-xtext_nightly/org.eclipse.xpect.target.eclipse_4_10_0-xtext_nightly.target, org.eclipse.xpect.releng/target-platforms/eclipse_4_10_0-xtext_nightly/pom.xml
added tp for 4.10 / Xtext Nightly
=> added tp for 4.10 / Xtext Nightly

org.eclipse.xpect.releng/maven-plugin-parent/pom.xml, org.eclipse.xtext.example.arithmetics.xpect.tests/pom.xml, org.eclipse.xtext.example.domainmodel.xpect.tests/pom.xml
=> drop 32 bit support

org.eclipse.xpect.releng/xtext-examples/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF, org.eclipse.xpect.releng/xtext-examples/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF, org.eclipse.xpect.tests/META-INF/MANIFEST.MF, org.eclipse.xpect/META-INF/MANIFEST.MF
=> widened asm ranges

org.eclipse.xpect.xtext.lib/META-INF/MANIFEST.MF, org.eclipse.xpect.xtext.lib/src/org/eclipse/xpect/xtext/lib/util/TokenSerializer.java, org.eclipse.xpect/src/org/eclipse/xpect/expectation/impl/CommaSeparatedValuesExpectationImpl.java, org.eclipse.xpect/src/org/eclipse/xpect/registry/FileExtensionInfoRegistry.java, org.eclipse.xpect/src/org/eclipse/xpect/registry/TestSuiteInfoRegistry.java, org.eclipse.xpect/src/org/eclipse/xpect/util/ResourceAccess.java
replaced Objects.toStringHelper with xbase.lib equivalent
=> replaced Objects.toStringHelper with xbase.lib equivalent

Jenkinsfile, org.eclipse.xpect.releng/maven-plugin-parent/pom.xml, org.eclipse.xpect.releng/maven-test-parent/pom.xml, org.eclipse.xpect.releng/xtext-examples/org.eclipse.xtext.example.arithmetics/src/org/eclipse/xtext/example/arithmetics/GenerateArithmetics.mwe2, org.eclipse.xpect.tests/src/org/eclipse/xpect/tests/FileExtensionInfoTest.xtend, org.eclipse.xpect/src/org/eclipse/xpect/registry/FileExtensionInfoRegistry.java, org.eclipse.xtext.example.arithmetics.xpect.tests/pom.xml, org.eclipse.xtext.example.domainmodel.xpect.tests/pom.xml
workaround for signature problem + tests on 4.10 + fixed tests
=> workaround for signature problem + tests on 4.10 + fixed tests

Jenkinsfile, org.eclipse.xpect.releng/target-platforms/eclipse_4_5_0-xtext_2_14_0/org.eclipse.xpect.target.eclipse_4_5_0-xtext_2_14_0.target, org.eclipse.xpect.releng/target-platforms/eclipse_4_5_0-xtext_2_14_0/pom.xml
=> build with mars and 2.14

Jenkinsfile
=> archive repository zip #258

org.eclipse.xpect.releng/maven-plugin-parent/pom.xml, org.eclipse.xpect.releng/xtext-examples/maven-parents/grammar-plugin/pom.xml, org.eclipse.xpect/pom.xml
drop old fornax plugin pulled from obsolte fornax repo
=> drop old fornax plugin pulled from obsolete fornax repo

Jenkinsfile
=> GH-269: NullPointerException in non-multi-branch Jenkins builds

README.md
=> fixed repo links

Jenkinsfile
replaced outdated node with current (fixes build not starting)
=> replaced outdated node with current (fixes build not starting)

Jenkinsfile
[#279] fix snapshot deployment
=> [#279] fix snapshot deployment

org.eclipse.xpect.releng/maven-plugin-parent/pom.xml, org.eclipse.xtext.example.arithmetics.xpect.tests/pom.xml, org.eclipse.xtext.example.domainmodel.xpect.tests/pom.xml, pom.xml
updated tycho version to 1.7.0
=> updated tycho version to 1.7.0

Jenkinsfile
=> [#286] fix build: use java 8

Jenkinsfile
=> updates for Jenkins

Jenkinsfile
=> run builds nightly

Jenkinsfile
=> fix jenkins deprecations

Jenkinsfile, org.eclipse.xpect.releng/target-platforms/eclipse_2020_06-xtext_nightly/org.eclipse.xpect.target.eclipse_2020_06-xtext_nightly.target
pull new separate xtext.generator feature in xtext nightly build
=> pull new separate xtext.generator feature in xtext nightly build

org.eclipse.xpect.xtext.lib/src/org/eclipse/xpect/xtext/lib/util/IFileUtil.java
=> Setup fails if the folder already exists

org.eclipse.xpect.releng/target-platforms/eclipse_2020_06-xtext_nightly/org.eclipse.xpect.target.eclipse_2020_06-xtext_nightly.target
use matching xtext and mwe versions
=> use matching xtext and mwe versions

Jenkinsfile, org.eclipse.xpect.releng/maven-plugin-parent/pom.xml
=> switch to centos 8

Jenkinsfile, org.eclipse.xpect.releng/target-platforms/eclipse_2020_06-xtext_nightly/org.eclipse.xpect.target.eclipse_2020_06-xtext_nightly.target
run build against Xtext nightly with Java 11
=> run build against Xtext nightly with Java 11

org.eclipse.xpect.releng/xtext-examples/org.eclipse.xtext.example.arithmetics/src/org/eclipse/xtext/example/arithmetics/GenerateArithmetics.mwe2
=> fix arith. workflow

org.eclipse.xpect.releng/target-platforms/eclipse_2020_06-xtext_nightly/org.eclipse.xpect.target.eclipse_2020_06-xtext_nightly.target
fix build against Xtext nightly
=> fix build against Xtext nightly

org.eclipse.xpect.releng/target-platforms/eclipse_2022_03-xtext_nightly/org.eclipse.xpect.target.eclipse_2022_03-xtext_nightly.target
=> repair broken build

org.eclipse.xpect.mwe2/src/org/eclipse/xpect/mwe2/StatefulLexerFragment.xtend
generate supresswarnings for stateful lexers
cc @tjeske
=> generate supresswarnings for stateful lexers

org.eclipse.xpect.ui/src/org/eclipse/xpect/ui/preferences/XpectRootPreferencePage.java
replaced the LIVE_TEST_EXECUTION_PREFERENEC_NAME with SKIP_CONTENT_CHECK_PREFERENCE_NAME
=> Fix wrong preference id usage

org.eclipse.xpect.ui.junit/src/org/eclipse/xpect/ui/junit/registry/WorkspaceTestSuiteInfoRegistry.java
=> fix pde depr.

org.eclipse.xpect.ui.junit/src/org/eclipse/xpect/ui/junit/launching/LaunchShortcutUtil.java
- changed from JUnitLaunchConfigurationConstants.ATTR_TEST_METHOD_NAME to ATTR_TEST_NAME
=> adjusted deprecated usage of ATTR_TEST_METHOD_NAME #371
